// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "TestADress1",
                            Email = "TestEmail1@gmail.com",
                            Name = "TestName1",
                            Password = "TestPassword1.",
                            PhoneNumber = "+37061111111",
                            Surname = "TestSurame1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "TestADress2",
                            Email = "TestEmail2@gmail.com",
                            Name = "TestName2",
                            Password = "TestPassword2.",
                            PhoneNumber = "+37062222222",
                            Surname = "TestSurame2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "TestADress3",
                            Email = "TestEmail3@gmail.com",
                            Name = "TestName3",
                            Password = "TestPassword3.",
                            PhoneNumber = "+37063333333",
                            Surname = "TestSurame3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
